In [1]:
import numpy as np

In [ ]:
arr  = np.array([1,2,3,4,5])

In [2]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])

In [3]:
arr1 + arr2

array([[5, 7, 9]])

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr[0:3]

array([1, 2, 3])

In [6]:
arr.shape

(6,)

In [7]:
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [10]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

In [11]:
np.dot(m1, m2)

array([[19, 22],
       [43, 50]])

In [12]:
np.mean(arr)

np.float64(3.5)

In [13]:
arr

array([1, 2, 3, 4, 5, 6])

In [14]:
np.std(arr)

np.float64(1.707825127659933)

In [15]:
np.random.rand(10)

array([0.87886874, 0.91209809, 0.43246354, 0.17571483, 0.47220703,
       0.2100537 , 0.49119365, 0.39446399, 0.87039189, 0.39111678])

In [16]:
arr = [1, 2, 3, np.nan, 5, 6]

In [17]:
arr

[1, 2, 3, nan, 5, 6]

In [18]:
np.isnan(arr)

array([False, False, False,  True, False, False])

In [19]:
import time

In [20]:
ls1 = list(range(100000000))
start = time.time()
sum(ls1)
end = time.time()
print(end-start)

0.44193053245544434


In [21]:
ls1 = np.array(ls1)
start = time.time()
np.sum(ls1)
end = time.time()
print(end-start)

0.06840968132019043
